name: Build bitcoin-sv

on:
  push:
    branches:    
      - master
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Installing dependencies
        run: |
          echo "brew install automake berkeley-db libtool boost openssl pkg-config libevent, please wait ... maybe it will be 10 mins..."
          brew install automake berkeley-db libtool boost openssl pkg-config libevent
        env: 
         destination: ${{ matrix.destination }}
       
      - name: Cloning Bitcoin SV
        env: 
          REPO_URL: https://github.com/bitcoin-sv/bitcoin-sv
          REPO_BRANCH: master
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH bitcoin-sv
        
      - name: Building Bitcoin SV - Autotools
        working-directory: ./bitcoin-sv
        run: |
          cd bitcoin-sv
          ./autogen.sh
          ./configure
          make
          
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: bitcoin-sv
          path: bitcoin-sv/build
